site_name: Color Project Docs
nav:
    - Installation: index.md
    - Configrations: Configrations.md
    - ColorCLI: colorcli.md
    - ColorDaemon: colord.md
    - Faucet: faucet.md
    - Explorer: Explorer_setup.md
    - JoinTestNet: joinTestNet.md
    - ChangeValidatorLogo: ChangeMonikerLogo.md
    - Ledger Nano Setup: ledgersetup.md
    - Ledger Nano Color App Setup: ledger-colors.md
    
theme: material


